service: s3-signed-func
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: us-east-2


functions:
  hello:
    handler: handler.get_signed_url

plugins:
  - serverless-python-requirements